name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: braulio94/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: edc88ab8ccdf194354b148fe700befb3
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
